IF EXISTS (SELECT * FROM SYS.databases WHERE name = 'EFF_2016_TH')
    DROP DATABASE EFF_2016_TH
CREATE DATABASE EFF_2016_TH
GO
USE EFF_2016_TH
GO
CREATE TABLE Etablissement
(
	codeEtab INT PRIMARY KEY,
    nomEtab VARCHAR(50),
    ville VARCHAR(50)
)
GO
CREATE TABLE